# Generated by Django 5.2.5 on 2025-09-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_user_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together={('patient', 'doctor')},
        ),
    ]
