# Generated by Django 5.2.5 on 2025-09-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0003_alter_patientdoctormapping_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
